//! Run 421 — F3/F4/F8 unavailable-authority fail-closed **release-binary
//! evidence driver** (Cargo example; NOT part of the `qbind-node` production
//! CLI).
//!
//! # Purpose
//!
//! Run 420 corrected the former Proposal/Vote `verification_ctx == None`
//! fail-open bypass in the binary-path consensus loop with an explicit typed
//! [`ConsensusVerificationPolicy`] (`Required` default, test-only
//! `LocalFixtureUnsigned`). Run 420 proved the correction with production-path
//! loop tests only; it did NOT capture standalone release-binary runtime
//! evidence (`RELEASE_BINARY_EVIDENCE=NOT-CAPTURED`).
//!
//! This helper produces that missing evidence. It drives real, loopback,
//! cross-process KEMTLS sessions against the deployed
//! `target/release/qbind-node` receiver (which has NO configured consensus
//! verification authority, so `verification_ctx == None` and the production
//! default `Required` policy is active) and lets the Run 421 harness observe
//! the deployed node's live `/metrics` reacting to a fixed, enumerated set of
//! consensus frames.
//!
//! It proves the **unavailable-authority fail-closed boundary** only: an
//! authenticated, F6-authorized Proposal/Vote is rejected because consensus
//! verification authority is unavailable. It does NOT — and cannot — prove
//! configured-authority cryptographic signature success, because no consensus
//! signing authority exists on the standalone binary.
//!
//! It changes **no** production behavior. It reuses the Run 419 driver's
//! material-generation and static-root/KEMTLS session patterns and only the
//! pre-existing public production APIs (`P2pNodeBuilder`, the `pqc_root_config`
//! loaders, the real `P2pMessage`/`ConsensusNetMsg` wire types, and the real
//! `qbind-wire` consensus encoders).
//!
//! # Safety envelope (enforced, not documented-only)
//!
//! * DevNet-only: every driver node is built with `NetworkEnvironment::Devnet`.
//!   MainNet/TestNet are impossible to select — there is no environment
//!   argument.
//! * Loopback-only: the receiver target and the driver's own listener must be
//!   `127.0.0.1`/`::1`; any other address exits non-zero before any socket is
//!   opened.
//! * Fixed enumerated scenarios only. There is **no** arbitrary-payload-hex,
//!   arbitrary-sender-selection, arbitrary-suite, arbitrary-signature, or
//!   general-purpose forged-message mode. The claimed-sender, signature shape,
//!   and suite id are hardcoded per scenario (driver = validator 1,
//!   impersonated victim = validator 0, receiver = validator 2).
//! * Bounded message count: each scenario sends at most a handful of frames.
//! * No secret logging: the helper never prints KEM secret keys, raw cert
//!   bytes, root public-key blobs, complete signatures, or absolute private
//!   paths. Only truncated NodeId prefixes and loopback endpoints are printed.
//! * Malformed arguments, a non-loopback target, or a scenario/connect failure
//!   exit non-zero.
//!
//! Temporary PQC material (root signing key held **in memory only**; leaf KEM
//! secret files created mode `0600`) is generated by the `gen-material`
//! subcommand into a caller-provided temp directory and removed by the harness.
//!
//! # Subcommands
//!
//! ```text
//! run_421_f3_f4_f8_release_binary_driver gen-material <DIR>
//! run_421_f3_f4_f8_release_binary_driver drive <SCENARIO> <MATERIAL_DIR> \
//!     <RECEIVER_LOOPBACK_ADDR> <DRIVER_LISTEN_LOOPBACK_ADDR> <OUT_FILE>
//! ```
//!
//! `SCENARIO` is one of:
//! `s2-proposal`, `s3-vote`, `s4-mismatch`, `s5-badsig`, `s6-badsuite`.

use std::env;
use std::fs;
use std::io::Write;
use std::net::IpAddr;
use std::path::{Path, PathBuf};
use std::process::exit;
use std::time::{Duration, Instant};

use qbind_crypto::{MlKem768Backend, KEM_SUITE_ML_KEM_768};
use qbind_hash::derive_node_id_from_pubkey;
use qbind_net::MutualAuthMode;
use qbind_node::p2p::{ConsensusNetMsg, NodeId, P2pMessage, P2pService};
use qbind_node::p2p_node_builder::{P2pNodeBuilder, P2pNodeContext};
use qbind_node::pqc_devnet_helper::{
    encode_cert, issue_leaf_delegation_cert, mint_devnet_root, LeafCertSpec,
};
use qbind_node::pqc_root_config::{
    parse_pqc_peer_leaf_cert_spec, parse_pqc_trusted_root_specs, PqcLeafCredentialPaths,
    PqcPeerLeafCert, PqcRootMode, PqcStaticRootConfig, PqcTrustedRoot,
    PQC_TRANSPORT_SUITE_ML_DSA_44,
};
use qbind_types::primitives::NetworkEnvironment;
use qbind_wire::consensus::{BlockHeader, BlockProposal, Vote};
use qbind_wire::io::WireEncode;
use qbind_wire::net::NetworkDelegationCert;

// Fixed enumerated identities (no arbitrary sender selection).
const DRIVER_VID: u64 = 1;
const VICTIM_VID: u64 = 0;
const RECEIVER_VID: u64 = 2;
const NUM_VALIDATORS: usize = 3;

// Fixed, non-arbitrary signature/suite shapes used by the enumerated scenarios.
// `MISSING` = empty (honest / missing signature). `MALFORMED` = a short fixed
// non-empty pattern that is NOT a valid consensus signature. `WRONG_SUITE` is a
// fixed unsupported suite id. None of these are caller-controllable.
const SIG_MISSING: &[u8] = &[];
const SIG_MALFORMED: &[u8] = &[0xABu8; 8];
const WRONG_SUITE_ID: u16 = 0x00EE;

fn die(msg: &str) -> ! {
    eprintln!("[run421-driver] FATAL: {}", msg);
    exit(2);
}

fn hex_lower(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        use std::fmt::Write as _;
        let _ = write!(s, "{:02x}", b);
    }
    s
}

/// Truncated (first 8 bytes) NodeId prefix — publish-safe.
fn node_id_prefix(node_id: &NodeId) -> String {
    hex_lower(&node_id.as_bytes()[..8])
}

fn write_file(path: &Path, contents: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create parent dir");
    }
    let mut f = fs::File::create(path).expect("create file");
    f.write_all(contents.as_bytes()).expect("write file");
}

/// Write a KEM secret key file with owner-only `0600` permissions.
fn write_secret_file(path: &Path, bytes: &[u8]) {
    fs::write(path, bytes).expect("write secret file");
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perm = fs::metadata(path).expect("stat secret file").permissions();
        perm.set_mode(0o600);
        fs::set_permissions(path, perm).expect("chmod 0600 secret file");
    }
}

/// The `qbind-val-<vid>` validator-identity bytes (mirrors the production
/// DevNet root helper's `vid_bytes`).
fn validator_id_bytes_for(vid: u64) -> [u8; 32] {
    let mut out = [0u8; 32];
    let s = format!("qbind-val-{}", vid);
    let n = s.len().min(32);
    out[..n].copy_from_slice(&s.as_bytes()[..n]);
    out
}

/// Assert the address is loopback (`127.0.0.1` / `::1`); exit non-zero
/// otherwise. Called before any socket is bound or dialed.
fn require_loopback(addr: &str) {
    let host = match addr.rsplit_once(':') {
        Some((h, _)) => h.trim_start_matches('[').trim_end_matches(']'),
        None => die(&format!("address '{}' is not host:port", addr)),
    };
    match host.parse::<IpAddr>() {
        Ok(ip) if ip.is_loopback() => {}
        _ => die(&format!(
            "refusing non-loopback address '{}': Run 421 is loopback-only",
            addr
        )),
    }
}

// ---------------------------------------------------------------------------
// Material generation (root in-memory only; leaf KEM secrets mode 0600).
// ---------------------------------------------------------------------------

/// Mint a fresh ML-DSA-44 root and per-validator ML-KEM-768 leaves for
/// validators 0/1/2. All certs are signed by the SAME in-memory root; the root
/// signing key is discarded when this process exits and never written to disk.
fn gen_material(dir: &Path) {
    fs::create_dir_all(dir).expect("mkdir material dir");
    let root = mint_devnet_root().expect("mint devnet root");
    let root_id_hex = hex_lower(&root.root_key_id);
    let trusted_spec = format!(
        "{}:{}:{}",
        root_id_hex,
        PQC_TRANSPORT_SUITE_ML_DSA_44,
        hex_lower(&root.root_pk)
    );
    write_file(&dir.join("trusted-root.spec"), &trusted_spec);
    write_file(&dir.join("root.id.hex"), &root_id_hex);

    let mint_leaf = |validator_id: [u8; 32], cert_name: &str, sk_name: &str| {
        let (kem_pk, kem_sk) = MlKem768Backend::generate_keypair().expect("ml-kem keygen");
        let spec = LeafCertSpec {
            validator_id,
            root_key_id: root.root_key_id,
            leaf_kem_suite_id: KEM_SUITE_ML_KEM_768,
            leaf_kem_pk: kem_pk,
            not_before: 0,
            not_after: u64::MAX,
            ext_bytes: vec![],
        };
        let cert = issue_leaf_delegation_cert(&spec, &root.root_sk).expect("issue leaf cert");
        fs::write(dir.join(cert_name), encode_cert(&cert)).expect("write cert");
        write_secret_file(&dir.join(sk_name), &kem_sk);
    };

    for vid in 0..NUM_VALIDATORS as u64 {
        mint_leaf(
            validator_id_bytes_for(vid),
            &format!("v{}.cert.bin", vid),
            &format!("v{}.kem.sk.bin", vid),
        );
    }

    println!(
        "gen_material_ok: root_id={} validators={}",
        root_id_hex, NUM_VALIDATORS
    );
}

// ---------------------------------------------------------------------------
// Static-root config loading (public production loaders).
// ---------------------------------------------------------------------------

fn load_trusted_roots(dir: &Path) -> Vec<PqcTrustedRoot> {
    let spec = fs::read_to_string(dir.join("trusted-root.spec")).expect("read trusted-root.spec");
    parse_pqc_trusted_root_specs(&[spec.trim().to_string()], true).expect("parse trusted root spec")
}

fn peer_leaf_cert(dir: &Path, vid: u64) -> PqcPeerLeafCert {
    let spec = format!(
        "{}:{}",
        vid,
        dir.join(format!("v{}.cert.bin", vid)).display()
    );
    parse_pqc_peer_leaf_cert_spec(&spec).expect("parse peer leaf cert spec")
}

/// Load the driver's static-root config for its authenticated validator-1
/// identity, dialing the receiver (validator 2).
fn driver_static_root_config(dir: &Path) -> PqcStaticRootConfig {
    let leaf = PqcLeafCredentialPaths {
        cert_path: dir.join("v1.cert.bin"),
        kem_sk_path: dir.join("v1.kem.sk.bin"),
    }
    .load()
    .expect("load driver leaf credentials");
    PqcStaticRootConfig {
        mode: PqcRootMode::PqcStaticRoot,
        trusted_roots: load_trusted_roots(dir),
        leaf_credentials: Some(leaf),
        peer_leaf_certs: vec![peer_leaf_cert(dir, RECEIVER_VID)],
    }
}

fn cert_derived_node_id_from_file(cert_path: &Path) -> NodeId {
    use qbind_wire::io::WireDecode;
    let bytes = fs::read(cert_path).expect("read cert file");
    let mut slice: &[u8] = &bytes;
    let cert = NetworkDelegationCert::decode(&mut slice).expect("decode cert");
    NodeId::new(derive_node_id_from_pubkey(&cert.leaf_kem_pk))
}

// ---------------------------------------------------------------------------
// Consensus frame builders (real wire encoders; controlled claimed sender,
// fixed per-scenario signature/suite shapes).
// ---------------------------------------------------------------------------

fn encode_wire<T: WireEncode>(t: &T) -> Vec<u8> {
    let mut out = Vec::new();
    t.encode(&mut out);
    out
}

fn proposal_frame(proposer: u64, suite_id: u16, signature: &[u8]) -> P2pMessage {
    let proposal = BlockProposal {
        header: BlockHeader {
            version: 1,
            chain_id: 1,
            epoch: 0,
            height: 0,
            round: 0,
            parent_block_id: [0xFF; 32],
            payload_hash: [0u8; 32],
            proposer_index: proposer as u16,
            suite_id,
            tx_count: 0,
            timestamp: 0,
            payload_kind: qbind_wire::PAYLOAD_KIND_NORMAL,
            next_epoch: 0,
            batch_commitment: [0u8; 32],
        },
        qc: None,
        txs: vec![],
        signature: signature.to_vec(),
    };
    P2pMessage::Consensus(ConsensusNetMsg::Proposal(encode_wire(&proposal)))
}

fn vote_frame(voter: u64, suite_id: u16, signature: &[u8]) -> P2pMessage {
    let vote = Vote {
        version: 1,
        chain_id: 1,
        epoch: 0,
        height: 0,
        round: 0,
        step: 0,
        block_id: [0u8; 32],
        validator_index: voter as u16,
        suite_id,
        signature: signature.to_vec(),
    };
    P2pMessage::Consensus(ConsensusNetMsg::Vote(encode_wire(&vote)))
}

// ---------------------------------------------------------------------------
// Driver node construction + connect.
// ---------------------------------------------------------------------------

fn make_config(listen_addr: &str, receiver_addr: &str) -> qbind_node::node_config::NodeConfig {
    use qbind_ledger::{FeeDistributionPolicy, MonetaryMode, SeigniorageSplit};
    use qbind_node::node_config::{
        DagCouplingMode, ExecutionProfile, FastSyncConfig, GenesisSourceConfig, MempoolDosConfig,
        MempoolEvictionConfig, MempoolMode, NetworkMode, NetworkTransportConfig, NodeConfig,
        P2pAntiEclipseConfig, P2pDiscoveryConfig, P2pLivenessConfig, SignerFailureMode, SignerMode,
        SlashingConfig, SnapshotConfig, StateRetentionConfig, ValidatorStakeConfig,
    };
    use qbind_node::p2p_diversity::DiversityEnforcementMode;

    NodeConfig {
        environment: NetworkEnvironment::Devnet,
        execution_profile: ExecutionProfile::VmV0,
        data_dir: None,
        network: NetworkTransportConfig {
            enable_p2p: true,
            max_outbound: 4,
            max_inbound: 8,
            gossip_fanout: 3,
            listen_addr: Some(listen_addr.to_string()),
            advertised_addr: None,
            static_peers: vec![format!("{}@{}", RECEIVER_VID, receiver_addr)],
            static_peer_consensus_keys: Vec::new(),
            discovery_enabled: false,
            discovery_interval_secs: 30,
            max_known_peers: 200,
            target_outbound_peers: 8,
            liveness_probe_interval_secs: 30,
            liveness_failure_threshold: 3,
            liveness_min_score: 30,
            diversity_mode: DiversityEnforcementMode::Off,
            max_peers_per_ipv4_prefix24: 2,
            max_peers_per_ipv4_prefix16: 8,
            min_outbound_diversity_buckets: 4,
            max_single_bucket_fraction_bps: 2500,
        },
        network_mode: NetworkMode::P2p,
        gas_enabled: false,
        enable_fee_priority: false,
        mempool_mode: MempoolMode::Fifo,
        dag_availability_enabled: false,
        dag_coupling_mode: DagCouplingMode::Off,
        stage_b_enabled: false,
        fee_distribution_policy: FeeDistributionPolicy::burn_only(),
        monetary_mode: MonetaryMode::Off,
        monetary_accounts: None,
        seigniorage_split: SeigniorageSplit::default(),
        state_retention: StateRetentionConfig::disabled(),
        snapshot_config: SnapshotConfig::disabled(),
        fast_sync_config: FastSyncConfig::disabled(),
        signer_mode: SignerMode::LoopbackTesting,
        signer_keystore_path: None,
        remote_signer_url: None,
        remote_signer_cert_path: None,
        remote_signer_client_cert_path: None,
        remote_signer_client_key_path: None,
        hsm_config_path: None,
        signer_failure_mode: SignerFailureMode::ExitOnFailure,
        mempool_dos: MempoolDosConfig::devnet_default(),
        mempool_eviction: MempoolEvictionConfig::devnet_default(),
        p2p_discovery: P2pDiscoveryConfig::devnet_default(),
        p2p_liveness: P2pLivenessConfig::devnet_default(),
        p2p_anti_eclipse: Some(P2pAntiEclipseConfig::devnet_default()),
        slashing: SlashingConfig::devnet_default(),
        validator_stake: ValidatorStakeConfig::devnet_default(),
        genesis_source: GenesisSourceConfig::devnet_default(),
        expected_genesis_hash: None,
    }
}

/// Build an authenticated (static-root Required) validator-1 driver node and
/// wait until the receiver's cert-derived NodeId is registered as a connected
/// peer.
async fn build_authenticated_driver(
    material_dir: &Path,
    listen_addr: &str,
    receiver_addr: &str,
) -> (P2pNodeContext, bool, bool, NodeId) {
    let config = make_config(listen_addr, receiver_addr);
    let pqc = driver_static_root_config(material_dir);
    let ctx = P2pNodeBuilder::new()
        .with_num_validators(NUM_VALIDATORS)
        .with_mutual_auth_mode(MutualAuthMode::Required)
        .with_pqc_root_config(pqc)
        .build(&config, DRIVER_VID)
        .await
        .expect("build authenticated driver node");
    let receiver_node_id = cert_derived_node_id_from_file(&material_dir.join("v2.cert.bin"));
    let (connected, saw_receiver) = wait_connected(&ctx, &receiver_node_id).await;
    (ctx, connected, saw_receiver, receiver_node_id)
}

async fn wait_connected(ctx: &P2pNodeContext, target: &NodeId) -> (bool, bool) {
    let deadline = Instant::now() + Duration::from_secs(20);
    let mut saw_target = false;
    while Instant::now() < deadline {
        let peers = ctx.p2p_service.connected_peers();
        if peers.contains(target) {
            saw_target = true;
            break;
        }
        if ctx.p2p_service.connected_peer_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    (ctx.p2p_service.connected_peer_count() > 0, saw_target)
}

/// Send `frames` to the receiver, pacing slightly so the deployed read/demux/
/// binary-consensus loop processes each before shutdown.
async fn send_frames(ctx: &P2pNodeContext, frames: &[P2pMessage]) {
    for frame in frames {
        ctx.p2p_service.broadcast(frame.clone());
        tokio::time::sleep(Duration::from_millis(150)).await;
    }
    tokio::time::sleep(Duration::from_millis(2000)).await;
}

struct DriveOutcome {
    connected: bool,
    saw_receiver: bool,
    frames_sent: usize,
    local_node_id_prefix: String,
    receiver_node_id_prefix: String,
    note: String,
}

/// The fixed frame list for each enumerated scenario. No caller input other
/// than the scenario name selects these.
fn scenario_frames(scenario: &str) -> Result<(Vec<P2pMessage>, &'static str), String> {
    let default_suite = qbind_wire::DEFAULT_CONSENSUS_SUITE_ID;
    match scenario {
        // Honest authenticated validator-1 Proposal with a missing signature.
        // F6 accepts; the Required unavailable-context gate rejects fail-closed.
        "s2-proposal" => Ok((
            vec![proposal_frame(DRIVER_VID, default_suite, SIG_MISSING)],
            "authenticated validator 1 honest Proposal(proposer=1) — expect inbound proposal context-unavailable rejection",
        )),
        // Honest authenticated validator-1 Vote with a missing signature.
        "s3-vote" => Ok((
            vec![vote_frame(DRIVER_VID, default_suite, SIG_MISSING)],
            "authenticated validator 1 honest Vote(voter=1) — expect inbound vote context-unavailable rejection",
        )),
        // F6 mismatch: authenticated as validator 1 but claiming validator 0.
        // F6 must reject BEFORE the Run 420 context gate for both message types.
        "s4-mismatch" => Ok((
            vec![
                proposal_frame(VICTIM_VID, default_suite, SIG_MISSING),
                vote_frame(VICTIM_VID, default_suite, SIG_MISSING),
            ],
            "authenticated validator 1 claiming validator 0 (Proposal+Vote) — expect claimed_sender_mismatch x2, context counters unchanged",
        )),
        // Malformed (non-empty, invalid) signatures. Under Required+None the
        // context gate still rejects before any signature parsing.
        "s5-badsig" => Ok((
            vec![
                proposal_frame(DRIVER_VID, default_suite, SIG_MALFORMED),
                vote_frame(DRIVER_VID, default_suite, SIG_MALFORMED),
            ],
            "authenticated validator 1 malformed-signature Proposal+Vote — expect context-unavailable rejection (no signature parsing)",
        )),
        // Wrong/unsupported suite id. Under Required+None the context gate still
        // rejects before any suite enforcement.
        "s6-badsuite" => Ok((
            vec![
                proposal_frame(DRIVER_VID, WRONG_SUITE_ID, SIG_MISSING),
                vote_frame(DRIVER_VID, WRONG_SUITE_ID, SIG_MISSING),
            ],
            "authenticated validator 1 wrong-suite Proposal+Vote — expect context-unavailable rejection (no suite enforcement)",
        )),
        other => Err(format!("unknown scenario '{}'", other)),
    }
}

async fn drive(
    scenario: &str,
    material_dir: &Path,
    receiver_addr: &str,
    listen_addr: &str,
) -> DriveOutcome {
    let (frames, note) = match scenario_frames(scenario) {
        Ok(v) => v,
        Err(e) => die(&e),
    };
    let (ctx, connected, saw, rid) =
        build_authenticated_driver(material_dir, listen_addr, receiver_addr).await;
    let local = ctx.p2p_service.local_node_id();
    let sent = if connected {
        send_frames(&ctx, &frames).await;
        frames.len()
    } else {
        0
    };
    let _ = P2pNodeBuilder::shutdown(ctx).await;
    DriveOutcome {
        connected,
        saw_receiver: saw,
        frames_sent: sent,
        local_node_id_prefix: node_id_prefix(&local),
        receiver_node_id_prefix: node_id_prefix(&rid),
        note: note.to_string(),
    }
}

fn usage() -> ! {
    eprintln!(
        "usage:\n  run_421_f3_f4_f8_release_binary_driver gen-material <DIR>\n  \
         run_421_f3_f4_f8_release_binary_driver drive <SCENARIO> <MATERIAL_DIR> \
         <RECEIVER_LOOPBACK_ADDR> <DRIVER_LISTEN_LOOPBACK_ADDR> <OUT_FILE>\n\n\
         SCENARIO ∈ s2-proposal | s3-vote | s4-mismatch | s5-badsig | s6-badsuite"
    );
    exit(2);
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        usage();
    }
    match args[1].as_str() {
        "gen-material" => {
            if args.len() != 3 {
                usage();
            }
            gen_material(&PathBuf::from(&args[2]));
        }
        "drive" => {
            if args.len() != 7 {
                usage();
            }
            let scenario = args[2].clone();
            let material_dir = PathBuf::from(&args[3]);
            let receiver_addr = args[4].clone();
            let listen_addr = args[5].clone();
            let out_file = PathBuf::from(&args[6]);
            require_loopback(&receiver_addr);
            require_loopback(&listen_addr);
            if !material_dir.is_dir() {
                die(&format!(
                    "material dir '{}' not found",
                    material_dir.display()
                ));
            }
            let rt = tokio::runtime::Builder::new_multi_thread()
                .enable_all()
                .build()
                .expect("tokio runtime");
            let outcome = rt.block_on(drive(
                &scenario,
                &material_dir,
                &receiver_addr,
                &listen_addr,
            ));
            let body = format!(
                "scenario: {}\nconnected: {}\nsaw_receiver_node_id: {}\nframes_sent: {}\n\
                 driver_node_id_prefix: {}\nreceiver_node_id_prefix: {}\nnote: {}\n",
                scenario,
                outcome.connected,
                outcome.saw_receiver,
                outcome.frames_sent,
                outcome.local_node_id_prefix,
                outcome.receiver_node_id_prefix,
                outcome.note,
            );
            write_file(&out_file, &body);
            print!("{}", body);
            if !outcome.connected {
                die(&format!(
                    "scenario '{}' did not establish a session",
                    scenario
                ));
            }
        }
        _ => usage(),
    }
}
