//! Run 419 — F6 standalone release-binary KEMTLS peer → consensus sender
//! binding **evidence driver** (Cargo example; NOT part of the `qbind-node`
//! production CLI).
//!
//! # Purpose
//!
//! Run 418 remediated finding **F6** (authenticated KEMTLS peer → consensus
//! sender binding) in production code and proved it with unit + in-process
//! demux-chain tests only. This helper produces the missing **standalone
//! release-binary** evidence: it drives a real, loopback, cross-process KEMTLS
//! session against the deployed `target/release/qbind-node` receiver and lets
//! the Run 419 harness observe the deployed node's live
//! `qbind_consensus_binding_total{result="…"}` `/metrics` family reacting to a
//! fixed, enumerated set of consensus frames.
//!
//! It changes **no** production behavior. It uses only pre-existing public
//! production APIs (`P2pNodeBuilder`, the `pqc_root_config` loaders, the real
//! `P2pMessage`/`ConsensusNetMsg` wire types, and the real `qbind-wire`
//! consensus encoders) and the same static-root KEMTLS framing path the
//! deployed binary uses.
//!
//! # Safety envelope (enforced, not documented-only)
//!
//! * DevNet-only: every driver node is built with `NetworkEnvironment::Devnet`.
//!   MainNet/TestNet are impossible to select — there is no environment
//!   argument.
//! * Loopback-only: the receiver target and the driver's own listener must be
//!   `127.0.0.1`/`::1`; any other address exits non-zero before any socket is
//!   opened.
//! * Fixed enumerated scenarios only. There is **no** arbitrary-payload-hex,
//!   arbitrary-sender-selection, or general-purpose forged-message mode. The
//!   claimed-sender values are hardcoded per scenario (driver = validator 1,
//!   impersonated victim = validator 0, receiver = validator 2).
//! * Bounded message count: each scenario sends at most a handful of frames.
//! * No secret logging: the helper never prints KEM secret keys, raw cert
//!   bytes, root public-key blobs, or absolute private paths. Only truncated
//!   NodeId prefixes and loopback endpoints are printed.
//! * Malformed arguments, a non-loopback target, or a scenario/connect failure
//!   exit non-zero.
//!
//! Temporary PQC material (root signing key held **in memory only**; leaf KEM
//! secret files created mode `0600`) is generated by the `gen-material`
//! subcommand into a caller-provided temp directory and removed by the harness.
//!
//! # Subcommands
//!
//! ```text
//! run_419_f6_release_binary_binding_driver gen-material <DIR>
//! run_419_f6_release_binary_binding_driver drive <SCENARIO> <MATERIAL_DIR> \
//!     <RECEIVER_LOOPBACK_ADDR> <DRIVER_LISTEN_LOOPBACK_ADDR> <OUT_FILE>
//! ```
//!
//! `SCENARIO` is one of:
//! `s1-honest`, `s2-impersonation`, `s3-newview`, `s6-alt-leaf`,
//! `s4-optional-unauth`, `s5-disabled-unauth`.

use std::env;
use std::fs;
use std::io::Write;
use std::net::IpAddr;
use std::path::{Path, PathBuf};
use std::process::exit;
use std::time::{Duration, Instant};

use bincode::Options as _;

use qbind_consensus::ids::ValidatorId;
use qbind_consensus::timeout::{TimeoutCertificate, TimeoutMsg};
use qbind_crypto::{MlKem768Backend, KEM_SUITE_ML_KEM_768};
use qbind_hash::derive_node_id_from_pubkey;
use qbind_net::MutualAuthMode;
use qbind_node::p2p::{
    ConsensusNetMsg, NodeId, P2pMessage, P2pService, RestoreCatchupRequest, RestoreCatchupResponse,
};
use qbind_node::p2p_node_builder::{P2pNodeBuilder, P2pNodeContext};
use qbind_node::pqc_devnet_helper::{
    encode_cert, issue_leaf_delegation_cert, mint_devnet_root, LeafCertSpec,
};
use qbind_node::pqc_root_config::{
    parse_pqc_peer_leaf_cert_spec, parse_pqc_trusted_root_specs, PqcLeafCredentialPaths,
    PqcPeerLeafCert, PqcRootMode, PqcStaticRootConfig, PqcTrustedRoot,
    PQC_TRANSPORT_SUITE_ML_DSA_44,
};
use qbind_types::primitives::NetworkEnvironment;
use qbind_wire::consensus::{BlockHeader, BlockProposal, Vote};
use qbind_wire::io::{WireDecode, WireEncode};
use qbind_wire::net::NetworkDelegationCert;

// Fixed enumerated identities (no arbitrary sender selection).
const DRIVER_VID: u64 = 1;
const VICTIM_VID: u64 = 0;
const RECEIVER_VID: u64 = 2;
const NUM_VALIDATORS: usize = 3;

fn die(msg: &str) -> ! {
    eprintln!("[run419-driver] FATAL: {}", msg);
    exit(2);
}

fn hex_lower(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        use std::fmt::Write as _;
        let _ = write!(s, "{:02x}", b);
    }
    s
}

/// Truncated (first 8 bytes) NodeId prefix — publish-safe.
fn node_id_prefix(node_id: &NodeId) -> String {
    hex_lower(&node_id.as_bytes()[..8])
}

fn write_file(path: &Path, contents: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create parent dir");
    }
    let mut f = fs::File::create(path).expect("create file");
    f.write_all(contents.as_bytes()).expect("write file");
}

/// Write a KEM secret key file with owner-only `0600` permissions.
fn write_secret_file(path: &Path, bytes: &[u8]) {
    fs::write(path, bytes).expect("write secret file");
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perm = fs::metadata(path).expect("stat secret file").permissions();
        perm.set_mode(0o600);
        fs::set_permissions(path, perm).expect("chmod 0600 secret file");
    }
}

/// The `qbind-val-<vid>` validator-identity bytes (mirrors the production
/// DevNet root helper's `vid_bytes`).
fn validator_id_bytes_for(vid: u64) -> [u8; 32] {
    let mut out = [0u8; 32];
    let s = format!("qbind-val-{}", vid);
    let n = s.len().min(32);
    out[..n].copy_from_slice(&s.as_bytes()[..n]);
    out
}

/// Assert the address is loopback (`127.0.0.1` / `::1`); exit non-zero
/// otherwise. Called before any socket is bound or dialed.
fn require_loopback(addr: &str) {
    let host = match addr.rsplit_once(':') {
        Some((h, _)) => h.trim_start_matches('[').trim_end_matches(']'),
        None => die(&format!("address '{}' is not host:port", addr)),
    };
    match host.parse::<IpAddr>() {
        Ok(ip) if ip.is_loopback() => {}
        _ => die(&format!(
            "refusing non-loopback address '{}': Run 419 is loopback-only",
            addr
        )),
    }
}

// ---------------------------------------------------------------------------
// Material generation (root in-memory only; leaf KEM secrets mode 0600).
// ---------------------------------------------------------------------------

/// Mint a fresh ML-DSA-44 root and per-validator ML-KEM-768 leaves for
/// validators 0/1/2 plus an ALTERNATE root-valid leaf for validator 1
/// (`v1_alt.*`) whose cert-derived NodeId differs from the configured
/// validator-1 NodeId. All certs are signed by the SAME in-memory root so the
/// alternate leaf is genuinely root-valid; the root signing key is discarded
/// when this process exits and never written to disk.
fn gen_material(dir: &Path) {
    fs::create_dir_all(dir).expect("mkdir material dir");
    let root = mint_devnet_root().expect("mint devnet root");
    let root_id_hex = hex_lower(&root.root_key_id);
    let trusted_spec = format!(
        "{}:{}:{}",
        root_id_hex,
        PQC_TRANSPORT_SUITE_ML_DSA_44,
        hex_lower(&root.root_pk)
    );
    write_file(&dir.join("trusted-root.spec"), &trusted_spec);
    write_file(&dir.join("root.id.hex"), &root_id_hex);

    let mint_leaf = |validator_id: [u8; 32], cert_name: &str, sk_name: &str| {
        let (kem_pk, kem_sk) = MlKem768Backend::generate_keypair().expect("ml-kem keygen");
        let spec = LeafCertSpec {
            validator_id,
            root_key_id: root.root_key_id,
            leaf_kem_suite_id: KEM_SUITE_ML_KEM_768,
            leaf_kem_pk: kem_pk,
            not_before: 0,
            not_after: u64::MAX,
            ext_bytes: vec![],
        };
        let cert = issue_leaf_delegation_cert(&spec, &root.root_sk).expect("issue leaf cert");
        fs::write(dir.join(cert_name), encode_cert(&cert)).expect("write cert");
        write_secret_file(&dir.join(sk_name), &kem_sk);
    };

    for vid in 0..NUM_VALIDATORS as u64 {
        mint_leaf(
            validator_id_bytes_for(vid),
            &format!("v{}.cert.bin", vid),
            &format!("v{}.kem.sk.bin", vid),
        );
    }
    // Alternate root-valid leaf for validator 1: same signed validator-id
    // (`qbind-val-1`), fresh KEM keypair → different cert-derived NodeId.
    mint_leaf(
        validator_id_bytes_for(DRIVER_VID),
        "v1_alt.cert.bin",
        "v1_alt.kem.sk.bin",
    );

    println!(
        "gen_material_ok: root_id={} validators={}",
        root_id_hex, NUM_VALIDATORS
    );
}

// ---------------------------------------------------------------------------
// Static-root config loading (public production loaders).
// ---------------------------------------------------------------------------

fn load_trusted_roots(dir: &Path) -> Vec<PqcTrustedRoot> {
    let spec = fs::read_to_string(dir.join("trusted-root.spec")).expect("read trusted-root.spec");
    parse_pqc_trusted_root_specs(&[spec.trim().to_string()], true).expect("parse trusted root spec")
}

fn peer_leaf_cert(dir: &Path, vid: u64) -> PqcPeerLeafCert {
    let spec = format!(
        "{}:{}",
        vid,
        dir.join(format!("v{}.cert.bin", vid)).display()
    );
    parse_pqc_peer_leaf_cert_spec(&spec).expect("parse peer leaf cert spec")
}

/// Load the driver's static-root config for its authenticated identity.
/// `leaf_stem` selects the on-disk leaf pair (e.g. `"v1"` or `"v1_alt"`).
fn driver_static_root_config(dir: &Path, leaf_stem: &str) -> PqcStaticRootConfig {
    let leaf = PqcLeafCredentialPaths {
        cert_path: dir.join(format!("{}.cert.bin", leaf_stem)),
        kem_sk_path: dir.join(format!("{}.kem.sk.bin", leaf_stem)),
    }
    .load()
    .expect("load driver leaf credentials");
    PqcStaticRootConfig {
        mode: PqcRootMode::PqcStaticRoot,
        trusted_roots: load_trusted_roots(dir),
        leaf_credentials: Some(leaf),
        // The dial target (receiver, validator 2) leaf cert so the KEMTLS
        // ClientInit knows the server's certified ML-KEM-768 public key.
        peer_leaf_certs: vec![peer_leaf_cert(dir, RECEIVER_VID)],
    }
}

fn cert_derived_node_id_from_file(cert_path: &Path) -> NodeId {
    let bytes = fs::read(cert_path).expect("read cert file");
    let mut slice: &[u8] = &bytes;
    let cert = NetworkDelegationCert::decode(&mut slice).expect("decode cert");
    NodeId::new(derive_node_id_from_pubkey(&cert.leaf_kem_pk))
}

// ---------------------------------------------------------------------------
// Consensus frame builders (real wire encoders; controlled claimed sender).
// ---------------------------------------------------------------------------

fn encode_wire<T: WireEncode>(t: &T) -> Vec<u8> {
    let mut out = Vec::new();
    t.encode(&mut out);
    out
}

fn proposal_frame(proposer: u64) -> P2pMessage {
    let proposal = BlockProposal {
        header: BlockHeader {
            version: 1,
            chain_id: 1,
            epoch: 0,
            height: 0,
            round: 0,
            parent_block_id: [0xFF; 32],
            payload_hash: [0u8; 32],
            proposer_index: proposer as u16,
            suite_id: qbind_wire::DEFAULT_CONSENSUS_SUITE_ID,
            tx_count: 0,
            timestamp: 0,
            payload_kind: qbind_wire::PAYLOAD_KIND_NORMAL,
            next_epoch: 0,
            batch_commitment: [0u8; 32],
        },
        qc: None,
        txs: vec![],
        signature: vec![],
    };
    P2pMessage::Consensus(ConsensusNetMsg::Proposal(encode_wire(&proposal)))
}

fn vote_frame(voter: u64) -> P2pMessage {
    let vote = Vote {
        version: 1,
        chain_id: 1,
        epoch: 0,
        height: 0,
        round: 0,
        step: 0,
        block_id: [0u8; 32],
        validator_index: voter as u16,
        suite_id: qbind_wire::DEFAULT_CONSENSUS_SUITE_ID,
        signature: vec![],
    };
    P2pMessage::Consensus(ConsensusNetMsg::Vote(encode_wire(&vote)))
}

fn timeout_frame(sender: u64) -> P2pMessage {
    let timeout: TimeoutMsg<[u8; 32]> = TimeoutMsg {
        view: 0,
        high_qc: None,
        validator_id: ValidatorId::new(sender),
        suite_id: qbind_wire::DEFAULT_CONSENSUS_SUITE_ID as u8,
        signature: vec![],
    };
    // Match the loop's `bincode::options().with_fixint_encoding()` decode.
    let bytes = bincode::options()
        .with_fixint_encoding()
        .serialize(&timeout)
        .expect("encode timeout");
    P2pMessage::Consensus(ConsensusNetMsg::Timeout(bytes))
}

fn newview_frame() -> P2pMessage {
    let tc: TimeoutCertificate<[u8; 32]> = TimeoutCertificate {
        view: 1,
        high_qc: None,
        signers: vec![],
        signed_timeouts: vec![],
        timeout_view: 0,
    };
    let bytes = bincode::options()
        .with_fixint_encoding()
        .serialize(&tc)
        .expect("encode timeout certificate");
    P2pMessage::Consensus(ConsensusNetMsg::NewView(bytes))
}

fn restore_request_frame(requester: u64) -> P2pMessage {
    P2pMessage::Consensus(ConsensusNetMsg::RestoreCatchupRequest(
        RestoreCatchupRequest {
            requester_validator_index: requester as u16,
            from_height: 0,
            from_block_id: [0u8; 32],
        },
    ))
}

fn restore_response_frame(responder: u64) -> P2pMessage {
    P2pMessage::Consensus(ConsensusNetMsg::RestoreCatchupResponse(
        RestoreCatchupResponse {
            responder_validator_index: responder as u16,
            request_from_height: 0,
            request_from_block_id: [0u8; 32],
            responder_committed_height: None,
            blocks: vec![],
        },
    ))
}

// ---------------------------------------------------------------------------
// Driver node construction + connect.
// ---------------------------------------------------------------------------

fn make_config(listen_addr: &str, receiver_addr: &str) -> qbind_node::node_config::NodeConfig {
    use qbind_ledger::{FeeDistributionPolicy, MonetaryMode, SeigniorageSplit};
    use qbind_node::node_config::{
        DagCouplingMode, ExecutionProfile, FastSyncConfig, GenesisSourceConfig, MempoolDosConfig,
        MempoolEvictionConfig, MempoolMode, NetworkMode, NetworkTransportConfig, NodeConfig,
        P2pAntiEclipseConfig, P2pDiscoveryConfig, P2pLivenessConfig, SignerFailureMode, SignerMode,
        SlashingConfig, SnapshotConfig, StateRetentionConfig, ValidatorStakeConfig,
    };
    use qbind_node::p2p_diversity::DiversityEnforcementMode;

    NodeConfig {
        environment: NetworkEnvironment::Devnet,
        execution_profile: ExecutionProfile::VmV0,
        data_dir: None,
        network: NetworkTransportConfig {
            enable_p2p: true,
            max_outbound: 4,
            max_inbound: 8,
            gossip_fanout: 3,
            listen_addr: Some(listen_addr.to_string()),
            advertised_addr: None,
            static_peers: vec![format!("{}@{}", RECEIVER_VID, receiver_addr)],
            static_peer_consensus_keys: Vec::new(),
            discovery_enabled: false,
            discovery_interval_secs: 30,
            max_known_peers: 200,
            target_outbound_peers: 8,
            liveness_probe_interval_secs: 30,
            liveness_failure_threshold: 3,
            liveness_min_score: 30,
            diversity_mode: DiversityEnforcementMode::Off,
            max_peers_per_ipv4_prefix24: 2,
            max_peers_per_ipv4_prefix16: 8,
            min_outbound_diversity_buckets: 4,
            max_single_bucket_fraction_bps: 2500,
        },
        network_mode: NetworkMode::P2p,
        gas_enabled: false,
        enable_fee_priority: false,
        mempool_mode: MempoolMode::Fifo,
        dag_availability_enabled: false,
        dag_coupling_mode: DagCouplingMode::Off,
        stage_b_enabled: false,
        fee_distribution_policy: FeeDistributionPolicy::burn_only(),
        monetary_mode: MonetaryMode::Off,
        monetary_accounts: None,
        seigniorage_split: SeigniorageSplit::default(),
        state_retention: StateRetentionConfig::disabled(),
        snapshot_config: SnapshotConfig::disabled(),
        fast_sync_config: FastSyncConfig::disabled(),
        signer_mode: SignerMode::LoopbackTesting,
        signer_keystore_path: None,
        remote_signer_url: None,
        remote_signer_cert_path: None,
        remote_signer_client_cert_path: None,
        remote_signer_client_key_path: None,
        hsm_config_path: None,
        signer_failure_mode: SignerFailureMode::ExitOnFailure,
        mempool_dos: MempoolDosConfig::devnet_default(),
        mempool_eviction: MempoolEvictionConfig::devnet_default(),
        p2p_discovery: P2pDiscoveryConfig::devnet_default(),
        p2p_liveness: P2pLivenessConfig::devnet_default(),
        p2p_anti_eclipse: Some(P2pAntiEclipseConfig::devnet_default()),
        slashing: SlashingConfig::devnet_default(),
        validator_stake: ValidatorStakeConfig::devnet_default(),
        genesis_source: GenesisSourceConfig::devnet_default(),
        expected_genesis_hash: None,
    }
}

/// Build an authenticated (static-root Required) driver node and wait until the
/// receiver's cert-derived NodeId is registered as a connected peer.
async fn build_authenticated_driver(
    material_dir: &Path,
    leaf_stem: &str,
    listen_addr: &str,
    receiver_addr: &str,
) -> (P2pNodeContext, bool, bool, NodeId) {
    let config = make_config(listen_addr, receiver_addr);
    let pqc = driver_static_root_config(material_dir, leaf_stem);
    let ctx = P2pNodeBuilder::new()
        .with_num_validators(NUM_VALIDATORS)
        .with_mutual_auth_mode(MutualAuthMode::Required)
        .with_pqc_root_config(pqc)
        .build(&config, DRIVER_VID)
        .await
        .expect("build authenticated driver node");
    let receiver_node_id = cert_derived_node_id_from_file(&material_dir.join("v2.cert.bin"));
    let (connected, saw_receiver) = wait_connected(&ctx, &receiver_node_id).await;
    (ctx, connected, saw_receiver, receiver_node_id)
}

/// Build an UNAUTHENTICATED driver node in the given mutual-auth mode, using the
/// default (non-static-root) transport so it presents **no** verified client
/// consensus certificate. Used for S4/S5: the session cannot present a verified
/// client consensus identity, so the receiver must fail closed on
/// `missing_origin`. Returns `(Some(ctx), connected)` on success, or
/// `(None, false)` if the transport cannot even establish an unauthenticated
/// session (recorded honestly as partial coverage — never substituted with an
/// in-process envelope).
async fn build_unauth_driver(
    _material_dir: &Path,
    mode: MutualAuthMode,
    listen_addr: &str,
    receiver_addr: &str,
) -> (Option<P2pNodeContext>, bool) {
    let config = make_config(listen_addr, receiver_addr);
    // No pqc_root_config → default transport, no client consensus certificate.
    let built = P2pNodeBuilder::new()
        .with_num_validators(NUM_VALIDATORS)
        .with_mutual_auth_mode(mode)
        .build(&config, DRIVER_VID)
        .await;
    match built {
        Ok(ctx) => {
            let connected = wait_any_peer(&ctx).await;
            (Some(ctx), connected)
        }
        Err(e) => {
            eprintln!(
                "[run419-driver] unauthenticated {:?} driver could not build: {} \
                 (recorded as partial coverage; no in-process substitution)",
                mode, e
            );
            (None, false)
        }
    }
}

async fn wait_connected(ctx: &P2pNodeContext, target: &NodeId) -> (bool, bool) {
    let deadline = Instant::now() + Duration::from_secs(20);
    let mut saw_target = false;
    while Instant::now() < deadline {
        let peers = ctx.p2p_service.connected_peers();
        if peers.contains(target) {
            saw_target = true;
            break;
        }
        if ctx.p2p_service.connected_peer_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    (ctx.p2p_service.connected_peer_count() > 0, saw_target)
}

async fn wait_any_peer(ctx: &P2pNodeContext) -> bool {
    let deadline = Instant::now() + Duration::from_secs(20);
    while Instant::now() < deadline {
        if ctx.p2p_service.connected_peer_count() > 0 {
            return true;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    ctx.p2p_service.connected_peer_count() > 0
}

/// Send `frames` to the receiver, pacing slightly so the deployed read/demux/
/// binary-consensus loop processes each before shutdown.
async fn send_frames(ctx: &P2pNodeContext, frames: &[P2pMessage]) {
    for frame in frames {
        ctx.p2p_service.broadcast(frame.clone());
        tokio::time::sleep(Duration::from_millis(150)).await;
    }
    // Drain time for the receiver's loop.
    tokio::time::sleep(Duration::from_millis(800)).await;
}

struct DriveOutcome {
    connected: bool,
    saw_receiver: bool,
    frames_sent: usize,
    local_node_id_prefix: String,
    receiver_node_id_prefix: String,
    note: String,
}

async fn drive(
    scenario: &str,
    material_dir: &Path,
    receiver_addr: &str,
    listen_addr: &str,
) -> DriveOutcome {
    match scenario {
        "s1-honest" => {
            let (ctx, connected, saw, rid) =
                build_authenticated_driver(material_dir, "v1", listen_addr, receiver_addr).await;
            let local = ctx.p2p_service.local_node_id();
            let frames = if connected {
                let f = vec![proposal_frame(DRIVER_VID)];
                send_frames(&ctx, &f).await;
                f.len()
            } else {
                0
            };
            let _ = P2pNodeBuilder::shutdown(ctx).await;
            DriveOutcome {
                connected,
                saw_receiver: saw,
                frames_sent: frames,
                local_node_id_prefix: node_id_prefix(&local),
                receiver_node_id_prefix: node_id_prefix(&rid),
                note: "authenticated validator 1 honest Proposal(proposer=1)".into(),
            }
        }
        "s2-impersonation" => {
            let (ctx, connected, saw, rid) =
                build_authenticated_driver(material_dir, "v1", listen_addr, receiver_addr).await;
            let local = ctx.p2p_service.local_node_id();
            let frames = if connected {
                // All five claimed-sender F6 branches, each claiming victim 0
                // while authenticated as validator 1.
                let f = vec![
                    proposal_frame(VICTIM_VID),
                    vote_frame(VICTIM_VID),
                    timeout_frame(VICTIM_VID),
                    restore_request_frame(VICTIM_VID),
                    restore_response_frame(VICTIM_VID),
                ];
                send_frames(&ctx, &f).await;
                f.len()
            } else {
                0
            };
            let _ = P2pNodeBuilder::shutdown(ctx).await;
            DriveOutcome {
                connected,
                saw_receiver: saw,
                frames_sent: frames,
                local_node_id_prefix: node_id_prefix(&local),
                receiver_node_id_prefix: node_id_prefix(&rid),
                note: "authenticated validator 1 claiming validator 0 across Proposal/Vote/Timeout/RestoreReq/RestoreResp".into(),
            }
        }
        "s3-newview" => {
            let (ctx, connected, saw, rid) =
                build_authenticated_driver(material_dir, "v1", listen_addr, receiver_addr).await;
            let local = ctx.p2p_service.local_node_id();
            let frames = if connected {
                let f = vec![newview_frame()];
                send_frames(&ctx, &f).await;
                f.len()
            } else {
                0
            };
            let _ = P2pNodeBuilder::shutdown(ctx).await;
            DriveOutcome {
                connected,
                saw_receiver: saw,
                frames_sent: frames,
                local_node_id_prefix: node_id_prefix(&local),
                receiver_node_id_prefix: node_id_prefix(&rid),
                note: "authenticated validator 1 NewView origin admission".into(),
            }
        }
        "s6-alt-leaf" => {
            // Alternate root-valid leaf for validator 1 (unconfigured NodeId).
            let (ctx, connected, saw, rid) =
                build_authenticated_driver(material_dir, "v1_alt", listen_addr, receiver_addr)
                    .await;
            let local = ctx.p2p_service.local_node_id();
            let frames = if connected {
                let f = vec![proposal_frame(DRIVER_VID)];
                send_frames(&ctx, &f).await;
                f.len()
            } else {
                0
            };
            let _ = P2pNodeBuilder::shutdown(ctx).await;
            DriveOutcome {
                connected,
                saw_receiver: saw,
                frames_sent: frames,
                local_node_id_prefix: node_id_prefix(&local),
                receiver_node_id_prefix: node_id_prefix(&rid),
                note: "root-valid but unconfigured alternate validator-1 leaf Proposal(proposer=1)"
                    .into(),
            }
        }
        "s4-optional-unauth" | "s5-disabled-unauth" => {
            let mode = if scenario == "s4-optional-unauth" {
                MutualAuthMode::Optional
            } else {
                MutualAuthMode::Disabled
            };
            let (maybe_ctx, connected) =
                build_unauth_driver(material_dir, mode, listen_addr, receiver_addr).await;
            let (local_prefix, frames) = match maybe_ctx {
                Some(ctx) => {
                    let local = ctx.p2p_service.local_node_id();
                    let sent = if connected {
                        let f = vec![proposal_frame(VICTIM_VID), newview_frame()];
                        send_frames(&ctx, &f).await;
                        f.len()
                    } else {
                        0
                    };
                    let _ = P2pNodeBuilder::shutdown(ctx).await;
                    (node_id_prefix(&local), sent)
                }
                None => (String::from("n/a"), 0),
            };
            DriveOutcome {
                connected,
                saw_receiver: false,
                frames_sent: frames,
                local_node_id_prefix: local_prefix,
                receiver_node_id_prefix: String::from("n/a"),
                note: format!(
                    "unauthenticated ingress under {:?}: Proposal + NewView",
                    mode
                ),
            }
        }
        other => die(&format!("unknown scenario '{}'", other)),
    }
}

fn usage() -> ! {
    eprintln!(
        "usage:\n  run_419_f6_release_binary_binding_driver gen-material <DIR>\n  \
         run_419_f6_release_binary_binding_driver drive <SCENARIO> <MATERIAL_DIR> \
         <RECEIVER_LOOPBACK_ADDR> <DRIVER_LISTEN_LOOPBACK_ADDR> <OUT_FILE>\n\n\
         SCENARIO ∈ s1-honest | s2-impersonation | s3-newview | s6-alt-leaf | \
         s4-optional-unauth | s5-disabled-unauth"
    );
    exit(2);
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        usage();
    }
    match args[1].as_str() {
        "gen-material" => {
            if args.len() != 3 {
                usage();
            }
            gen_material(&PathBuf::from(&args[2]));
        }
        "drive" => {
            if args.len() != 7 {
                usage();
            }
            let scenario = args[2].clone();
            let material_dir = PathBuf::from(&args[3]);
            let receiver_addr = args[4].clone();
            let listen_addr = args[5].clone();
            let out_file = PathBuf::from(&args[6]);
            require_loopback(&receiver_addr);
            require_loopback(&listen_addr);
            if !material_dir.is_dir() {
                die(&format!(
                    "material dir '{}' not found",
                    material_dir.display()
                ));
            }
            let rt = tokio::runtime::Builder::new_multi_thread()
                .enable_all()
                .build()
                .expect("tokio runtime");
            let outcome = rt.block_on(drive(
                &scenario,
                &material_dir,
                &receiver_addr,
                &listen_addr,
            ));
            let body = format!(
                "scenario: {}\nconnected: {}\nsaw_receiver_node_id: {}\nframes_sent: {}\n\
                 driver_node_id_prefix: {}\nreceiver_node_id_prefix: {}\nnote: {}\n",
                scenario,
                outcome.connected,
                outcome.saw_receiver,
                outcome.frames_sent,
                outcome.local_node_id_prefix,
                outcome.receiver_node_id_prefix,
                outcome.note,
            );
            write_file(&out_file, &body);
            print!("{}", body);
            // A scenario that never connected (except the intentionally
            // fail-closed unauth modes, which the harness evaluates from the
            // receiver's /metrics) is a driver-side failure.
            if !outcome.connected && !scenario.contains("unauth") {
                die(&format!(
                    "scenario '{}' did not establish a session",
                    scenario
                ));
            }
        }
        _ => usage(),
    }
}
